environment:
  - box:
      dim: [0.5, 0.5, 1]
      pos: [0.55, 0.55, 0.5]
  - box:
      dim: [0.5, 0.5, 1]
      pos: [-0.55, 0.55, 0.5]
  - box:
      dim: [0.5, 0.5, 1]
      pos: [0.55, -0.55, 0.5]
  - box:
      dim: [0.5, 0.5, 1]
      pos: [-0.55, -0.55, 0.5]

robot:
  # start: [0,    1.57, 0, 0, 0, 0, 0, 0, 0, 0]
  # goal:  [3.14, 1.57, 0, 0, 0, 0, 0, 0, 0, 0]
  # start: [0,    1.57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  # goal:  [3.14, 1.57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  start: [0,    1.57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  goal:  [3.14, 1.57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  
testing:
  max_num: 1000                                               # Maximal number of tests that should be carried out
  max_vel_obs: 0.3                                            # Maximal velocity for each obstacle from "environment"